[server]
port = 9000
host = "0.0.0.0"

[database]
path = "./data.db"

[nginx]
bin = "C:/Users/Hongyu/nginx/nginx-1.30.3/nginx.exe"
config = "C:/Users/Hongyu/nginx/nginx-1.30.3/conf/nginx.conf"
sites_enabled = "C:/Users/Hongyu/nginx/nginx-1.30.3/conf/sites-enabled"

[acme]
bin = "/root/.acme.sh/acme.sh"

[auth]
jwt_secret = "change-this-to-a-random-secret-key"
jwt_expires_hours = 24
